language: rust

os:
    - linux
    - osx
    - windows


rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly
        - os: windows
        - os: osx
    fast_finish: true

cache: cargo 
