[package]
name = "sss-rs"
version = "0.1.1"
authors = ["Aaron Flores <aaronjflores962@gmail.com"]
edition = "2018"
description = "A purely functional (as in working) implementation of Shamir Secret Sharing"
repository = "https://github.com/bilowik/sss-rs"
categories = ["cryptography"]
license-file = "LICENSE"
readme = "README.md"

[badges]
travis-ci = { repository = "https://travis-ci.com/bilowik/sss-rs", branch = "master" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
lazy_static = "1.3.0"
num-traits = "0.2.8"
num-bigint-dig = {version = "0.4.0", features = ["rand", "prime"]}
rust-crypto = "0.2.36"
