[package]
name = "sss-rs"
version = "0.1.0"
authors = ["bilowik"]
edition = "2018"
description = "A purely functional implementation of Shamir Secret Sharing"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
lazy_static = "1.3.0"
pretty_assertions = "0.6.1"
backtrace = "0.3.35"
bitfield="0.13.2"
num-traits = "0.2.8"
num-bigint-dig = {version = "0.4.0", features = ["rand", "prime"]}
signal-hook = "0.1.10"
console = "*"
